foodIngredients/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :foods

  root 'welcome#index'

end

foodIngredients/app/models/food.rb
class Food < ActiveRecord::Base
end

foodIngredients/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

foodIngredients/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def new
	end
	def create
		@food=Food.new(params.require(:food).permit(:name,:protein,:fat))
		@food.save
		redirect_to @food
	end
	def show
		@food=Food.find(params[:id])
	end
end

foodIngredients/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

foodIngredients/app/helpers/application_helper.rb
module ApplicationHelper
end

foodIngredients/app/helpers/foods_helper.rb
module FoodsHelper
end

foodIngredients/app/helpers/welcome_helper.rb
module WelcomeHelper
end

foodIngredients/app/views/foods/new.html.erb
<h1><center>New Food</center></h1>
<%= form_for :food, url: foods_path do |f| %>
	<p>
	<%= f.label(:name)%>
	<%= f.text_field(:name)%>
	</p>

	<p>
	<%= f.label(:protein)%>
	<%= f.text_field(:protein)%>
	</p>

	<p>
	<%= f.label(:fat)%>
	<%= f.text_field(:fat)%>
	</p>

	<p>
	<%= f.submit %>
	</p>
<% end %>

foodIngredients/app/views/foods/show.html.erb
<h1><center>New Food Added</center></h1>
<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>
 
<p>
  <strong>Protein:</strong>
  <%= @food.protein %>gm/100gm
</p>
<p>
  <strong>Fat:</strong>
  <%= @food.fat %>gm/100gm
</p>

foodIngredients/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodIngredients</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

foodIngredients/app/views/welcome/index.html.erb
<h1>Welcome TO Foods Ingredient</h1>